#title in header
title: "Brain Forest"

#main info
#owner
owner: "Francisco Sanabria"
email: fco.sanabria08@gmail.com
info: "I like dogs and tea. I'm from Costa Rica ğŸ‡¨ğŸ‡·"
#description
desc: "My name is Francisco Sanabria. Iâ€™m currently working at IBM as System engineer, EDI & B2B specialist and IBM Cloud practitioner. I like containers and itâ€™s technologies. Iâ€™m a visual artist, and a music producer.
You will find Spanish and English content mixed. :)
"
#menu
menu:
  Works: /projects
  About: /about
  Portfolio: /portfolio
#index/main page max show posts (in number)
max_post: 5

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/piktonus97m
linkedin: https://www.linkedin.com/in/francisco-sanabria-almendarez-445584150/
twitter: https://twitter.com/piktonus97x
instagram: https://www.instagram.com/piktonus97m/

# Misc
nanobar: /js/nanobar.min.js
switch_light: ğŸŒš
switch_dark: ğŸŒ

# favicon
favicon: /images/favicon.ico
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
